version: 0.2

phases:
  pre_build:
    commands:
      - 'echo "Deploying Infrastructure Stack"'
      - 'echo "Project: $PROJECT_NAME"'
      - 'INFRASTRUCTURE_STACK_NAME="${PROJECT_NAME}-infrastructure"'
      - |
        DOMAIN_NAME=$(python3 -c 'import json; print(json.load(open("infra/pipeline-parameters.json")).get("DomainName",""))')
        ACM_CERTIFICATE_ARN=$(python3 -c 'import json; print(json.load(open("infra/pipeline-parameters.json")).get("AcmCertificateArn",""))')
        HOSTED_ZONE_ID=$(python3 -c 'import json; print(json.load(open("infra/pipeline-parameters.json")).get("HostedZoneId",""))')

        if [ -z "$DOMAIN_NAME" ]; then
          echo "Missing DomainName in infra/pipeline-parameters.json"
          exit 1
        fi
        if [ -z "$ACM_CERTIFICATE_ARN" ] || echo "$ACM_CERTIFICATE_ARN" | grep -q '^REPLACE_WITH_'; then
          echo "Missing AcmCertificateArn in infra/pipeline-parameters.json (replace placeholder)"
          exit 1
        fi
        if [ -z "$HOSTED_ZONE_ID" ] || echo "$HOSTED_ZONE_ID" | grep -q '^REPLACE_WITH_'; then
          echo "Missing HostedZoneId in infra/pipeline-parameters.json (replace placeholder)"
          exit 1
        fi

        echo "Domain: $DOMAIN_NAME"
      
  build:
    commands:
      - |
        # Deploy or update infrastructure stack
        echo "Deploying infrastructure stack: $INFRASTRUCTURE_STACK_NAME"

        # Check if stack exists
        if aws cloudformation describe-stacks --stack-name $INFRASTRUCTURE_STACK_NAME --region $AWS_DEFAULT_REGION >/dev/null 2>&1; then
          STACK_STATUS=$(aws cloudformation describe-stacks \
            --stack-name $INFRASTRUCTURE_STACK_NAME \
            --region $AWS_DEFAULT_REGION \
            --query 'Stacks[0].StackStatus' \
            --output text)
          echo "Existing stack status: $STACK_STATUS"

          if [ "$STACK_STATUS" = "ROLLBACK_COMPLETE" ]; then
            echo "Stack is in ROLLBACK_COMPLETE; deleting before recreate..."
            aws cloudformation delete-stack \
              --stack-name $INFRASTRUCTURE_STACK_NAME \
              --region $AWS_DEFAULT_REGION
            aws cloudformation wait stack-delete-complete \
              --stack-name $INFRASTRUCTURE_STACK_NAME \
              --region $AWS_DEFAULT_REGION
            echo "Deleted. Creating fresh stack..."
            aws cloudformation create-stack \
              --stack-name $INFRASTRUCTURE_STACK_NAME \
              --template-body file://infra/infrastructure.yaml \
              --parameters \
                ParameterKey=ProjectName,ParameterValue=$PROJECT_NAME \
                ParameterKey=DomainName,ParameterValue=$DOMAIN_NAME \
                ParameterKey=AcmCertificateArn,ParameterValue=$ACM_CERTIFICATE_ARN \
                ParameterKey=HostedZoneId,ParameterValue=$HOSTED_ZONE_ID \
              --capabilities CAPABILITY_NAMED_IAM \
              --region $AWS_DEFAULT_REGION
            aws cloudformation wait stack-create-complete \
              --stack-name $INFRASTRUCTURE_STACK_NAME \
              --region $AWS_DEFAULT_REGION
          else
          echo "Stack exists, updating..."
          UPDATE_OUTPUT=$(aws cloudformation update-stack \
            --stack-name $INFRASTRUCTURE_STACK_NAME \
            --template-body file://infra/infrastructure.yaml \
            --parameters \
              ParameterKey=ProjectName,ParameterValue=$PROJECT_NAME \
              ParameterKey=DomainName,ParameterValue=$DOMAIN_NAME \
              ParameterKey=AcmCertificateArn,ParameterValue=$ACM_CERTIFICATE_ARN \
              ParameterKey=HostedZoneId,ParameterValue=$HOSTED_ZONE_ID \
            --capabilities CAPABILITY_NAMED_IAM \
            --region $AWS_DEFAULT_REGION 2>&1) || true

          if echo "$UPDATE_OUTPUT" | grep -q "No updates are to be performed"; then
            echo "No changes to infrastructure stack; skipping wait."
          else
            echo "$UPDATE_OUTPUT"
            aws cloudformation wait stack-update-complete \
              --stack-name $INFRASTRUCTURE_STACK_NAME \
              --region $AWS_DEFAULT_REGION
          fi
          fi
        else
          echo "Stack does not exist, creating..."
          aws cloudformation create-stack \
            --stack-name $INFRASTRUCTURE_STACK_NAME \
            --template-body file://infra/infrastructure.yaml \
            --parameters \
              ParameterKey=ProjectName,ParameterValue=$PROJECT_NAME \
              ParameterKey=DomainName,ParameterValue=$DOMAIN_NAME \
              ParameterKey=AcmCertificateArn,ParameterValue=$ACM_CERTIFICATE_ARN \
              ParameterKey=HostedZoneId,ParameterValue=$HOSTED_ZONE_ID \
            --capabilities CAPABILITY_NAMED_IAM \
            --region $AWS_DEFAULT_REGION

          if ! aws cloudformation wait stack-create-complete \
            --stack-name $INFRASTRUCTURE_STACK_NAME \
            --region $AWS_DEFAULT_REGION; then
            echo "Create failed. Recent stack events:"
            aws cloudformation describe-stack-events \
              --stack-name $INFRASTRUCTURE_STACK_NAME \
              --region $AWS_DEFAULT_REGION \
              --max-items 25 || true
            exit 1
          fi
        fi
      
      - |
        # Get outputs
        RESUME_BUCKET=$(aws cloudformation describe-stacks \
          --stack-name $INFRASTRUCTURE_STACK_NAME \
          --region $AWS_DEFAULT_REGION \
          --query 'Stacks[0].Outputs[?OutputKey==`ResumeBucket`].OutputValue' \
          --output text)
        
        WEBSITE_URL=$(aws cloudformation describe-stacks \
          --stack-name $INFRASTRUCTURE_STACK_NAME \
          --region $AWS_DEFAULT_REGION \
          --query 'Stacks[0].Outputs[?OutputKey==`WebsiteURL`].OutputValue' \
          --output text)

        CLOUDFRONT_DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
          --stack-name $INFRASTRUCTURE_STACK_NAME \
          --region $AWS_DEFAULT_REGION \
          --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' \
          --output text)
        
        echo "Resume Bucket: $RESUME_BUCKET"
        echo "Website URL: $WEBSITE_URL"
        echo "CloudFront Distribution ID: $CLOUDFRONT_DISTRIBUTION_ID"
      
      - |
        # Deploy website files to S3
        if [ -d "app" ]; then
          echo "Deploying website files to S3..."
          aws s3 sync ./app s3://$RESUME_BUCKET --delete
          
          # Set proper content types
          aws s3 cp s3://$RESUME_BUCKET/index.html s3://$RESUME_BUCKET/index.html \
            --metadata-directive REPLACE --content-type "text/html" --cache-control "public, max-age=60"
          aws s3 cp s3://$RESUME_BUCKET/style.css s3://$RESUME_BUCKET/style.css \
            --metadata-directive REPLACE --content-type "text/css" --cache-control "public, max-age=3600"
          aws s3 cp s3://$RESUME_BUCKET/resume.json s3://$RESUME_BUCKET/resume.json \
            --metadata-directive REPLACE --content-type "application/json" --cache-control "public, max-age=3600"

          # CloudFront invalidation so users see updates immediately
          if [ -n "$CLOUDFRONT_DISTRIBUTION_ID" ] && [ "$CLOUDFRONT_DISTRIBUTION_ID" != "None" ]; then
            echo "Creating CloudFront invalidation..."
            aws cloudfront create-invalidation \
              --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
              --paths "/*"
          else
            echo "Skipping invalidation: CloudFrontDistributionId not found in stack outputs."
          fi
        fi
      
  post_build:
    commands:
      - 'echo "Infrastructure deployment completed on $(date)"'
      - 'echo "Website is live at: $WEBSITE_URL"'
